--02/05/2025
--Aidan Cox
--enables equipment factories

local co = require("Modules.Settings")

function init(self)
	if co.resume then
		msg.post("main:/IO#IO", "load")
		msg.post("Inventory#Inventory", "loadItemData")
	end
end

function fixed_update(self, dt)
	
end

function on_message(self, message_id, message)
	
	if message_id == hash("EquipEnable") then
		factory.create("#" .. message.name)
	end

	if message_id == hash("unequip") then
		go.delete("#" .. message.name)
	end
end