--02/05/2025
--Aidan Cox
--enables equipment factories

local load

function init(self)
	msg.post("main:/IO#IO", "load")
	msg.post("Inventory#Inventory", "loadItemData")
end

function fixed_update(self, dt)
end

function on_message(self, message_id, message)
	if message_id == hash("EquipEnable") then
		factory.create("#" .. message.name)
	end

	if message_id == hash("start") then
		print("start recieved")
		
	end
end